"""Update models for auction and item

Revision ID: f60fd01226ef
Revises: cf3d3e26e03d
Create Date: 2024-09-03 00:05:41.188817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60fd01226ef'
down_revision = 'cf3d3e26e03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('provenance_origin', sa.String(length=100), nullable=True),
    sa.Column('provenance_previous_ownership', sa.Text(), nullable=True),
    sa.Column('authentication_details', sa.Text(), nullable=True),
    sa.Column('certificates', sa.Text(), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('rarity', sa.String(length=100), nullable=True),
    sa.Column('edition', sa.String(length=100), nullable=True),
    sa.Column('starting_bid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reserve_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
